### ISSUE TITLE
Configurable URL settings

### ISSUE THREAD

**Issue by vincep5** [jojoduquartier/MMM-RAIN-RADAR#1]
It would be nice to allow the user (via config) to set the radar color, map color, etc.  Not sure what all the URL params mean but I see that:
oFA=loop speed
c=radar color
rmt=map color
oAP=0 means just the latest image

You can set defaults for the params in your main .js file and allow the user to add in their config overrides if they choose to.

I like this module and I would really like to have the ability to have the map's latest image instead of the looping.  The looping animation eats up my CPU

**Comment by jojoduquartier** [comment]
Thanks for making the changes. Magic Mirror is my way of throwing myself into practicing and getting better at javascript. I plan on adding some new changes later and hopefully you can vet them as well.

**Comment by vincep5** [comment]
Cool thanks. Have fun!
