### ISSUE TITLE
Only header loads

### ISSUE THREAD

**Issue by mathiaswscott** [jojoduquartier/MMM-RAIN-RADAR#3]
The only thing that seems to load is the header. I tried disabling all of the default and 3rd party modules and still nothing as you can see in the attached screenshot. I check to see if there was any conflicting settings in the javascript file and I didn't find anything.
![2019-05-31-075408_1920x1080_scrot](https://user-images.githubusercontent.com/50928322/58707285-113d7580-837a-11e9-989a-0d2c1b311eff.png)

any ideas?

**Comment by jojoduquartier** [comment]
Hi,

I will look into this but could you try this commit: 87705f66a26dc28cad7ad7bdf2f6efa9ed65ff39
You shouldn't have to disable any other module and technically if the header is shown then so should the radar but I will look more into it. Thank you

**Comment by jojoduquartier** [comment]
@mathiaswscott I don't seem to have any problems with the module on my pi. Could you try `npm start dev` and see what you have in the console? Inspect the frame element.

**Comment by mathiaswscott** [comment]
The console and the frame element seem fine. I loaded the webpage in chromium and it load fine except for the flash. I dont know if chromium comes with a default flash but some say it does and you have to manually enable it. I've tried updating chormium and raspbian with no success.
![2019-06-06-085638_1920x1080_scrot](https://user-images.githubusercontent.com/50928322/59042180-9673cf00-883f-11e9-9970-e141a937eec3.png)

**Comment by mathiaswscott** [comment]
Nevermind it was my VPN that was causing problems. Sorry for the trouble
