### ISSUE TITLE
Keeps showing NJ when I put in NH coordinates.

### ISSUE THREAD

**Issue by aunrea** [jojoduquartier/MMM-RAIN-RADAR#6]
For some reason, the radar keeps showing NJ instead of NH. I have the coordinates set to:

latitude: 42.836330,
longitude: -71.649500,
area: "NH",

**Comment by jojoduquartier** [comment]
Hi Aunrea. Sorry for the late reply.
The area is only for this api `https://api.weather.gov/alerts/active/area/NH`. I think you need a higher zoom level. I think`zoomLevel = 8` works well like this: https://www.rainviewer.com/map.html?loc=42.836330,-71.649500,8.

The area will only be used to check if there are any severe weather alerts. If there are no alerts then the radar will disappear (at least I hope :))

**Comment by aunrea** [comment]
It always centered on New York City no matter what coordinates I put in. I ended up forking the module and hardcoding the coordinates into the iframe url in the code. That works perfectly.
