### ISSUE TITLE
Map Size?

### ISSUE THREAD

**Issue by dxfan227** [jojoduquartier/MMM-RAIN-RADAR#7]
Any way to control the size of the map? Mine is very long.

**Comment by jojoduquartier** [comment]
Hi. I am not sure if you can control the map size. Do you mean the div dimension?

**Comment by dxfan227** [comment]
I tried to change the div size and I think it worked but it did not change the size of the map just allowed the following div to over lap it.
What is the name or class of the div supposed to be.

**Comment by jojoduquartier** [comment]
That's odd. All I can think of is the `zoomLevel` option in the config. You could also use set `width` and `height` parameters in the config file since they are used to set the `iframe`'s width and height.

**Comment by Irish53** [comment]
In MMM-RAIN-RADAR.js I changed iframe.style = "border:0;height:50vh"; to iframe.style = "border:0;height:25vh"; to shrink the height to fit my setup.
